version: "3"

tasks:
  switch:
    desc: Switch environment
    platforms: [linux/amd64, darwin/arm64]
    cmds:
      - cmd: home-manager switch --flake .
        platforms: [linux/amd64]
      - cmd: sudo darwin-rebuild switch --flake '.#MBP16'
        platforms: [darwin/arm64]

  update:
    desc: Update pkgs
    cmds:
      - cmd: nix flake update nixpkgs
      - cmd: echo "Update complete, run 'task' to switch"
