format="""
$all$directory
$character
"""

[character]
success_symbol = "🦄 "
error_symbol = "❌ "

[git_branch]
symbol = "🌱 "

[package]
disabled = true

[[battery.display]]
#バッテリーを表示するタイミング、表示する際の文字のスタイル
threshold = 100
style = "bold blue"

[battery]
#バッテリーの各状態のアイコン、上からフル充電、充電中、バッテリー残量低下
full_symbol = "🤗 "
charging_symbol = "😌 "
discharging_symbol = "😨 "

[time]
#時間の表示をオンにして12時間表示に
disabled = false
use_12hr = true
